apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:wGzDCE+p7Z0fHE8=,iv:oIk1BC9/UDLyipt1djjm1alR2r9xitW5kQvcBGOwOh8=,tag:puoTyLUA9mYU+yx0BkxY8w==,type:str]
  SECRET_DOMAIN_CC: ENC[AES256_GCM,data:pzDkjb5saExayQ==,iv:kCecQiNQqh3KUt3L6orC5rLSB2Tgudpv4/Ao9aNOdzE=,tag:0x8DesufW/WXSeiUMnysuA==,type:str]
  SECRET_DOMAIN_CO: ENC[AES256_GCM,data:jtSuqb/jdsu1jA==,iv:2j/bx4k+yoFzaaCp5Qvl0p+dHd/3colTK/rbHGAwd4A=,tag:Gv5qCCBqV79OqTP/0lHEJw==,type:str]
  SECRET_DOMAIN_TV: ENC[AES256_GCM,data:zUJ2hrNhnLOngg==,iv:FM2eswcdElwhCkQkPWFdrAX5AnFkRk3hvz6UMt/JgJE=,tag:phJB5i6ZvxvKD5E6v0jNsw==,type:str]
  AUTHELIA_SENDER: ENC[AES256_GCM,data:cysr7HlQhxpgS3NIvehQgh3acdARrBm6AMG+,iv:EbqQambSvS+v7JDoYG8FoB2WFAvyngM+/G++bifIB50=,tag:qe8DrseudA8O0NXw0RmTBg==,type:str]
  SMTP_USER: ENC[AES256_GCM,data:LPdYE0n8Jx0MJveUkOQnWQ==,iv:3Sz23Za5UBjt0NJHl1/8CN5mXYnxxOblQ0JzNp7UhkU=,tag:2lt7AgeFAaA5ku3DfEQ9nw==,type:str]
  NFS_SERVER: ENC[AES256_GCM,data:m2B36xCwyBjUJ+Y=,iv:DZU2mysvo6OWMJrKijI44hGCMVkoU64CbK63DvLX8vw=,tag:sKcnIOWQS9tt/Lum+yFDQw==,type:str]
  NFS_DOWNLOAD: ENC[AES256_GCM,data:+3NRgpBEtfYsf0HhFkGZ8S4=,iv:bT5iPvDhYkTOFbIVaVq6bYR6Y5JdrES+MSWQWlIKHtM=,tag:LyBFaXpALQjKsAz533pfrQ==,type:str]
  NFS_MUSIC: ENC[AES256_GCM,data:htrs3omrzhDBsBuFofQ=,iv:CsS+jjPRQQ7WKJwrMGxlPP86QYCZm0u/MMh5yeDM3vk=,tag:uS4Ibu84MQ1z7y2y0iekpw==,type:str]
  NFS_MEDIA: ENC[AES256_GCM,data:WJiuJ8QjJYSoW9cjjNk=,iv:nUB9BvW7ZnxegpfFYBFur9qIcbq2K2HHKTuFmiXNb98=,tag:p0gl5zb3sZDMCYnyWECorw==,type:str]
  NFS_BOOKS: ENC[AES256_GCM,data:E7Uf+asIH2WyIyDmFsk=,iv:JZXD+RhiiFiMlksAKuqQhtJkR+X8i/kEph8+WZRdLsk=,tag:FUhwvzupoTel0TehKKOoAw==,type:str]
  NFS_KUBERNETES: ENC[AES256_GCM,data:AMPtyNIhtedByujlQE+RlyMVWA==,iv:Hl3XP36t2Fomhn0gPFfo9sB7C+cKi4aeRy9JpQW8mJQ=,tag:truQrFLfDodWVy/QG6zB1A==,type:str]
  NFS_CSI_VOL: ENC[AES256_GCM,data:bCtX4+nvk3qHtZQ6RJYWuiKTxg==,iv:Yzf7TvbKkQ7eSqQ2FPdfLI7aPYF5J+QL6YGxM/7/IPg=,tag:eTZNb3H1pZiC/gYEbXxMEw==,type:str]
  NFS_SUBDIR_VOL: ENC[AES256_GCM,data:9OA1yihnYWtqg2DEnCF9wVbXxNOTh5U=,iv:pJP/LiW90CQXJC8QRjCjVkxUiQ/voVEBJ3GySz+zfPk=,tag:jAPe2luOrdaHpYhDCWSzng==,type:str]
  EMAIL: ENC[AES256_GCM,data:rani5R6vqCktrN169wFQNQ==,iv:e9Yp+40ck90xCWlUT9dUf8zow+wGXjtNvS79FE6Umrc=,tag:Cm4jI7W7a4k1g/0k6nTisA==,type:str]
  NETWORK_K8S_CLUSTER_CIDR: ENC[AES256_GCM,data:bySBGHR2F0yk407C,iv:mUwiDikYfLdIeKWPc8bYx4BVyKzIGF727P5MAdmMzPs=,tag:Ka5AS5zQ36d/HR41ROI1uQ==,type:str]
  NETWORK_K8S_SERVICE_CIDR: ENC[AES256_GCM,data:01ERy8z5CwVDBxLO,iv:4QTD/bcgwIDjTQq6Z+lDHU4lxDZRAuROgK6KPrz5/ms=,tag:yYGzzFqb1Tg/OMLJ+ZaHHQ==,type:str]
  SECRET_WIREGUARD_PORT: ENC[AES256_GCM,data:BMWrkVI=,iv:NLsnLROHaS4rG+a5Eqor1ag6BzbUQL+NRqMkvPwCxf4=,tag:YxjoQEjtPJuJGyiZDVsU9Q==,type:str]
  NETWORK_SERVER_CIDR: ENC[AES256_GCM,data:Qzr9Z7e10gPzAA==,iv:cHTAPe6bmhRUX8//Ktd3HP4zj1t2K3L3i3YnOLGG6iY=,tag:MSBR0ETp5HC9yNPDDk9IEw==,type:str]
  WORKSTATION_CIDR: ENC[AES256_GCM,data:VoVLzrl3mn500LX/ZaQ=,iv:J99Jd2nudMTTgPSyaOCohIbUc4SDo1my32q/WQZwFXs=,tag:0y13Pe+Q7STOKrwEPyqZRQ==,type:str]
  SECRET_PASSWORD: ENC[AES256_GCM,data:h6Er+RF3GrQ=,iv:TaSWmH/HeV+TSQekPPb2S+T4Mh04DLe83nAnwJJCoS4=,tag:FE3SBWXzRDw3Du/0GPUgAg==,type:str]
  SECRET_QB_USERNAME: ENC[AES256_GCM,data:cpUfyN8=,iv:bZxtFOl0c0HFbKky1Ee6aD0j8LDFi4tH+op7VTRZQAY=,tag:gnwKDiGGHMdXfcVskiJmWw==,type:str]
  SECRET_QB_PASSWORD: ENC[AES256_GCM,data:wrtVN3XKd7Y=,iv:NldGY2PZpjn6w1mjbCmpMAi0Y0gCxoyn3pAy6j9H1CY=,tag:5/f9eRZAL4mFxBNdhaq0Eg==,type:str]
  NFS_MINIO: ENC[AES256_GCM,data:wjIKKINGS01RjJBLINs=,iv:IfqWrKal6kETFacmyd3ZSlLbFBfqrnJoh7oxzZOIiJ8=,tag:RNjPN+41bf4vnLC3ZLKqcg==,type:str]
  SECRET_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:8e2hkJ5fPaI=,iv:2Wuq5lm/YQbmLZMgr8BBGrjhnkNhBTivcYeeLl96x6o=,tag:LwClGpJMllpL2wO2GEUg+A==,type:str]
  SECRET_POSTGRESQL_ROOT_PASSWORD: ENC[AES256_GCM,data:KGXQxZhzORw=,iv:/LqgEnI8kJGS4jJEagWBgaoUeUcG/fFKdjyGXv4BYNI=,tag:OEbxNUZMPdgiTrdo+LhVFw==,type:str]
  SECRET_KOPIA_PASSWORD: ENC[AES256_GCM,data:QWtvJRGS9nQ=,iv:EppsiGEK617UtrL5apyMSMb15yJS6l1BKTLD1YzeV2g=,tag:ilBSGhdm3X3cyK/82vqryQ==,type:str]
  SECRET_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ryPLWyK5KxBLn/EoYsJIkWeNxqtZb4F69M0=,iv:Tm1EkLT5R3BNcReUlXaCw8+OuMdkb1KKaz5LtZGF62w=,tag:+3yZhSjbhy+rASFf00fgkg==,type:str]
  TZ: ENC[AES256_GCM,data:WKnsjDegZZYDhZ4Qh41K3q4fOk4=,iv:FFKHlayqO1mZN30yTai4SsBF26i7axtm6Sr+sARUt5M=,tag:YUPt8yPWNXB50xWr/3n18g==,type:str]
  SECRET_CLOUDFLARE_TUNNEL: ENC[AES256_GCM,data:EIWdGLsnS53oBG+05G0tCJxaKtNdn9SZz6aOIqAsgScsO0upOTPz0NGwYjS/vEKxC8Ix830=,iv:y3Qw83eVoSnZmZIbhTVicsSTQrvdh0adJYxYsZhzfgA=,tag:46oZ3KqK6BYfuDk0tEde1g==,type:str]
  HARDWARE_DOMAIN: ENC[AES256_GCM,data:QQ5uUmT5pKLblw==,iv:T1dAWNEJIfm2ZwVsJSB5T6BQVLxC9zQkB6lyr6x1kUg=,tag:lV7vkq6PEY4LuYCwGEAs7g==,type:str]
  CLUSTER_NAME: ENC[AES256_GCM,data:kBsDz6qKEA==,iv:E5YUEmbRhib1MzOHNtWcyVz5yl5JbAwu9TKPCJkwQvI=,tag:ZzU8QMtYb4vWccVaHN7f6g==,type:str]
  VNC_USER: ENC[AES256_GCM,data:qDts68s=,iv:PL+Fge348Z70Cd4yapY9GnI0msFTKXDLv0L678TJPmI=,tag:URFEW8XkecZyVqcfm1ZJoA==,type:str]
  VNC_PASSWORD: ENC[AES256_GCM,data:Y39H+4JdwkY=,iv:Ku4k6FJtz2JwPLh361ZK6IREMhc3KKoHhy7YpuR1yXI=,tag:X1GfGX5/0EMtSHrYPKECkQ==,type:str]
  SECRET_BOOKSTACK_DATABASE_PASSWORD: ENC[AES256_GCM,data:VUu0djECC7k=,iv:6CJY0gkWBmgwHxRR6M7CWINpR9fKC8kW5oWLKkfpA1Y=,tag:jTtOdI5vF8q/6XodzS6DdQ==,type:str]
  SECRET_RANCHER_ADMIN_PASSWORD: ENC[AES256_GCM,data:LaBT1U+brzQ=,iv:CQ9y67JLwKFP7zALTPNr3XaVprmiYDCgwThI5D8+5iI=,tag:I0+NAVfQp6KAZmy9hoMVyA==,type:str]
  INFLUXDB_ADMIN_USER: ENC[AES256_GCM,data:gmsIOW8=,iv:vtM+tZwizNsEe8yI/U8zx6CrAIALlQ9gp7cfyqm46jo=,tag:D7BGhYSYsdxvimn9zhpt3w==,type:str]
  INFLUXDB_ADMIN_USER_PASSWORD: ENC[AES256_GCM,data:ExxQNyVd9GQ=,iv:7zgE/LZ7DPLGKP1P6Y9VVHoSO6nsloJb9ce2LE7qG28=,tag:kOsMddUDsTlg5ZIihSA4Og==,type:str]
  INFLUXDB_ADMIN_USER_TOKEN: ENC[AES256_GCM,data:wo6QAWqCxKEj4w==,iv:uOQXs54aLiC/iLi32K53prTN1qpbyoGbSGAACJOukUI=,tag:BLW6v7ZCBaGm/gILJ3fXiQ==,type:str]
  PGADMIN_EMAIL: ENC[AES256_GCM,data:m3n2by9gSIiLolfslDHUFw==,iv:7nGVY6f07DABJVT0RvonvN8LwogVQeWQTftrBJ7EENU=,tag:SmIJxTB8ahKfA4OnPHi57Q==,type:str]
  PGADMIN_PASSWORD: ENC[AES256_GCM,data:vfj5mznhNqQ=,iv:CFyvU8Xh7/JEAz3/HdNK2E2nXTIBBfwp36eWygd7ShY=,tag:+Ym9kcmkbHMCzpSMjcM/IQ==,type:str]
  AUTHELIA_SMTP_PASS: ENC[AES256_GCM,data:DwF4yM4hIY9hfCcOPCHuaQ==,iv:GFsNZ86cofLiluSElWkjyQq1Nz/OWtaJAEvD4fqFlBQ=,tag:kqiGy0T8M5ntavTuKR5a5w==,type:str]
  SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:9jpX6Fvv4LdKjVQ=,iv:Qf8Est2igZT4BBHKpUY8FzMWdgkvnf7pCQFGf0XlC0o=,tag:rzQSVh/c2bIvaEdp7PI8/Q==,type:str]
  SECRET_OUTLINE_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:ZbiehqG91mX4t43C9eRyGNWBJmeBb5V7xW4=,iv:JBpIyn/MVasGjjwbyoMQQsWa06lGm2YgaA4Axbao1/I=,tag:bfgHvc/Gv9bXoBQMTfOZyg==,type:str]
  OUTLINE_POSTGRES_PASS: ENC[AES256_GCM,data:2SXF4IjpJ3+jHx20fkwpr5QqnEYIPTrn2T0=,iv:twUCrNboCU6h+C2RUlSbc4IsZX4MQ3BsrBKRBeQDLjk=,tag:kCfUiLmpEj7/Wr1LP1PBZg==,type:str]
  OUTLINE_POSTGRES_USER: ENC[AES256_GCM,data:f87WuMiqGA==,iv:FfsDtW9A+QNQ3FzaHtHTFyoofiykAu3Uf6d2TfKvPvM=,tag:ZlA6nhDBeNv1z3nigGtFbg==,type:str]
  SECRET_GITEA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:1Ara9JUraoMmfRUjRk/c+h/23hqCD38KG3g=,iv:YuKQ23XLS1Xm1Hi0g5G/Nxf80o+YD29SAb66NPojIsc=,tag:rUL78FFQ0CPyHfIfWQxyVg==,type:str]
  SABNZBD_API: ENC[AES256_GCM,data:AayOPz9Pvp4+QhJBUq6auLSGst+YLQSQzbu/2RfgzDU=,iv:BV+LOrwwOKUtz3T3e/F7+nPEV4wk+/aORnnaKKiMyNU=,tag:7h5/sGZxf4O2K9gC927ptQ==,type:str]
  SYNO_ADMIN: ENC[AES256_GCM,data:QXa+o+8L8bE=,iv:k5iyGSK2sc8Z+0kVTJr84aarVUoRvSNH+bqM9YPNUgU=,tag:wjjZBoffJVShDNv1H9MkcA==,type:str]
  SYNO_PASSWORD: ENC[AES256_GCM,data:Y8/kLOoHltc=,iv:9MG8DtYRQ5MYhF5EE2NcpK39vE+l9JydN5GyPIS928s=,tag:4+Ai8xoBWIMr4W6hC6Fyow==,type:str]
  NAS_SERVER: ENC[AES256_GCM,data:9kSvpvc7M97gIPk=,iv:tOIVPYE0Or84Hip7bud/baYFo0djiVXuFzVNyagvzAs=,tag:T/KpBEMXQ2WAERMsjtVAAA==,type:str]
  QNAP: ENC[AES256_GCM,data:uCE8fuIm5gW/ZW0=,iv:4Y8E3M3nQzqH2jRZK3yNcB1Sh0rUXD8W9Lfi04tsHxk=,tag:e58fvJT1NnJO31R655pPQA==,type:str]
  CUSTOM_WEB_PORT: ENC[AES256_GCM,data:Pnnqaw==,iv:Y0+2Hahf4InyRtqhz0nCe79PrL+53tQaXl90IKprTDE=,tag:qWITOFX3YUPUIg0uA3ejAA==,type:str]
sops:
  age:
    - recipient: age1x04pdgvml4flx5lewxkqhp3rfngzlgt6gnhqnydskf9u9zhf7euq4qxxxs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuM3EwQTB0Q2tTeE5hOTd5
        NklDMW43WlpwYkFCd2oxamZlYTVNN3Noa3pRClVDRWxBTURVK1ZlbnUrTkNkazhW
        TkVlcGNwRXJGVzRqUm9wWlA1dE5wSlUKLS0tIEQ2SEk0ZDFFdFY3ekpzS3dqS0VO
        MGs2YTRPNVl2czRnOGcwaXRkamZwN2sKdAOqzbOR9AIafMvypcwM70P9T+2dLyCw
        cKvlNsG8vfv/Mt4U2d/eLeFhY+2TmePr4+AhDLtAbDNp84xdgrYcGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T03:03:14Z"
  mac: ENC[AES256_GCM,data:K3RcGHQzKRJYhoCllqmwCATimF225CUDIgzjMBUmII0N+4anHxhsZQ0i23o2eY8pS7uwqhpA06XgWZ0eG9Q92BkiUu5WBAcxg5lvRjteSl2ubhlbIvviGDc3kU6MrcLu4q6OisfqsvQZhFqYPIe/VSYaSfA/9vQY2l2WcOgMdiI=,iv:nPuB1WHxJNFKZbLiE7RsQqEUHDuthq+nYv++IM/Eijk=,tag:+GId54vl0ikgePGgbyPepA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
