---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vpn
resources:
  - ./device-plugin.yaml
  - ./helmrelease.yaml.100
  - ./externalsecret.yaml
#  - ./ocirepository.yaml
#  - ./networkpolicy.yaml
