---
apiVersion: v1
kind: Namespace
metadata:
  name: organizers
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
  annotations:
    volsync.backube/privileged-movers: "true"
    routed-gateway: true
